// Labels for the temple-side onboarding form (app/onboard). Thai is the default; English is the
// same form for offices or monks who prefer it (techno 2026-09-27). Values sent to the API never change.
export type OnboardLang = "th" | "en";

export const ONBOARD_COPY = {
  th: {
    badLink: "ลิงก์ไม่ถูกต้อง กรุณาเปิดจากแชท LINE อีกครั้ง",
    failed: (status: number) => `ส่งไม่สำเร็จ (${status})`,
    saved: "บันทึกเรียบร้อยแล้ว",
    pending: "รอสำนักงานวัดยืนยัน",
    close: "ปิดหน้านี้แล้วกลับไปที่แชท LINE ได้เลย",
    titleOffice: "ลงทะเบียนสำนักงานวัด",
    titleMonk: "แจ้งชื่อเพื่อรับกิจนิมนต์",
    time: "ใช้เวลาประมาณ 2 นาที",
    contact: "ชื่อผู้ติดต่อ",
    monkName: "ชื่อ / ฉายา",
    temple: "วัด",
    otherTemple: "— วัดอื่น (พิมพ์ชื่อด้านล่าง) —",
    templeName: "ชื่อวัด",
    monks: "รายชื่อพระที่รับกิจนิมนต์ (บรรทัดละหนึ่งรูป)",
    services: "กิจที่รับ",
    areas: "พื้นที่ที่เดินทางไปได้",
    languages: "ภาษาที่สนทนาได้ (นอกจากภาษาไทย)",
    weekly: "วันเวลาที่สะดวก (ทุกสัปดาห์)",
    saving: "กำลังบันทึก…",
    save: "บันทึก",
    switchLabel: "ภาษา / Language",
  },
  en: {
    badLink: "This link is not valid. Please open it again from the LINE chat.",
    failed: (status: number) => `Could not save (${status})`,
    saved: "Saved",
    pending: "Waiting for the temple office to confirm",
    close: "You can close this page and go back to the LINE chat.",
    titleOffice: "Register your temple office",
    titleMonk: "Sign up to receive invitations",
    time: "Takes about 2 minutes",
    contact: "Contact name",
    monkName: "Name / monastic name",
    temple: "Temple",
    otherTemple: "— Another temple (type its name below) —",
    templeName: "Temple name",
    monks: "Monks who accept invitations (one per line)",
    services: "Ceremonies you accept",
    areas: "Areas you can travel to",
    languages: "Languages you can talk in (besides Thai)",
    weekly: "Usual free times (every week)",
    saving: "Saving…",
    save: "Save",
    switchLabel: "Language / ภาษา",
  },
} as const;
